using AlxCourseHomework;
using AlxCourseHomework.MaterialsAssignements.Storage;
using AlxCourseHomework.Nowy_folder;

//Console.WriteLine("──────────────────────────────────────────────────────────────────");
//Console.WriteLine("Page 12");
//Console.WriteLine("─────────────────────────────────");
//Exercise1Run.RunEx1();
//Exercise2Run.RunEx2();
//Console.WriteLine("──────────────────────────────────────────────────────────────────");
//Console.WriteLine("Page 17");
//Console.WriteLine("─────────────────────────────────");
//Exercise3Run.RunEx3();
//Console.WriteLine("──────────────────────────────────────────────────────────────────");
//Console.WriteLine("Page 19");
//Console.WriteLine("────────────────");
//Exercise4Run.RunEx4();
//Console.WriteLine("──────────────────────────────────────────────────────────────────");
//Console.WriteLine("Mailing service homework");
//Console.WriteLine("────────────────");
//Homework1Test.Run();
/*
Console.WriteLine("Page 21 Ex. 1");
Console.WriteLine("──────────────────────────────────────────────────────────────────");
StorageTest1.Run();
Console.WriteLine("────────────────");
Console.WriteLine("Page 21 Ex. 2");
Console.WriteLine("──────────────────────────────────────────────────────────────────");
NumberDivisions.Run();
Console.WriteLine("────────────────");
Console.WriteLine("Page 23 Ex. 1");
Console.WriteLine("──────────────────────────────────────────────────────────────────");
StoreTest1.Run();
Console.WriteLine("────────────────");
Console.WriteLine("Page 23 Ex. 2");
Console.WriteLine("──────────────────────────────────────────────────────────────────");
Matrix3x3.Run();
Console.WriteLine("────────────────");
Console.WriteLine("Page 23 Ex. 3");
Console.WriteLine("──────────────────────────────────────────────────────────────────");
MultipledArray.Run();
Console.WriteLine("────────────────");
Console.WriteLine("Page 25 Ex. 1");
Console.WriteLine("──────────────────────────────────────────────────────────────────");
ShowMonths.Run1();
Console.WriteLine("────────────────");
Console.WriteLine("Page 25 Ex. 2");
Console.WriteLine("──────────────────────────────────────────────────────────────────");
ShowMonths.Run2();
Console.WriteLine("────────────────");
*/
Console.WriteLine("────────────────");
Console.WriteLine("Page 45 Ex. 1");
Console.WriteLine("──────────────────────────────────────────────────────────────────");
CarPriceCalculator.Run();
Console.WriteLine("────────────────");

